/*
###############################################################
#  Generated by:      Cadence Innovus 20.14-s095_1
#  OS:                Linux x86_64(Host ID vlsi14.sastra.edu)
#  Generated on:      Thu Dec 11 18:54:24 2025
#  Design:            siso
#  Command:           saveNetlist siso_route_netlist.v
###############################################################
*/
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Dec 11 2025 18:13:10 IST (Dec 11 2025 12:43:10 UTC)
// Verification Directory fv/siso 
module siso (
	clk, 
	rst, 
	d, 
	qout, 
	qb);
   input clk;
   input rst;
   input d;
   output qout;
   output qb;

   // Internal wires
   wire FE_PHN1_w_6;
   wire [7:0] w;
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;

   CLKBUFX2 FE_PHC1_w_6 (.A(w[6]),
	.Y(FE_PHN1_w_6));
   DFFSRHQX1 d7_qb_reg (.CK(clk),
	.D(n_2),
	.Q(qb),
	.RN(n_1),
	.SN(n_3));
   NAND2XL g38__2398 (.A(n_2),
	.B(n_0),
	.Y(n_3));
   NAND2XL g37__5107 (.A(qout),
	.B(n_0),
	.Y(n_1));
   DFFRHQX1 d6_qout_reg (.CK(clk),
	.D(w[5]),
	.Q(w[6]),
	.RN(rst));
   DFFRHQX1 d5_qout_reg (.CK(clk),
	.D(w[4]),
	.Q(w[5]),
	.RN(rst));
   DFFRHQX1 d4_qout_reg (.CK(clk),
	.D(w[3]),
	.Q(w[4]),
	.RN(rst));
   DFFRHQX1 d3_qout_reg (.CK(clk),
	.D(w[2]),
	.Q(w[3]),
	.RN(rst));
   DFFRHQX1 d2_qout_reg (.CK(clk),
	.D(w[1]),
	.Q(w[2]),
	.RN(rst));
   DFFRHQX1 d1_qout_reg (.CK(clk),
	.D(w[0]),
	.Q(w[1]),
	.RN(rst));
   DFFRHQX1 d0_qout_reg (.CK(clk),
	.D(d),
	.Q(w[0]),
	.RN(rst));
   INVXL g48 (.A(rst),
	.Y(n_0));
   DFFRX1 d7_qout_reg (.CK(clk),
	.D(FE_PHN1_w_6),
	.Q(qout),
	.QN(n_2),
	.RN(rst));
endmodule

