
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Dec 11 2025 19:06:25 IST (Dec 11 2025 13:36:25 UTC)

// Verification Directory fv/siso 
`timescale 1ns/10ps
module siso(clk, rst, d, qout, qb);
  input clk, rst, d;
  output qout, qb;
  wire clk, rst, d;
  wire qout, qb;
  wire [7:0] w;
  wire n_0, n_1, n_2, n_3;
  DFFSRHQX1 d7_qb_reg(.RN (n_1), .SN (n_3), .CK (clk), .D (n_2), .Q
       (qb));
  NAND2XL g38__2398(.A (n_2), .B (n_0), .Y (n_3));
  NAND2XL g37__5107(.A (qout), .B (n_0), .Y (n_1));
  DFFRHQX1 d6_qout_reg(.RN (rst), .CK (clk), .D (w[5]), .Q (w[6]));
  DFFRHQX1 d5_qout_reg(.RN (rst), .CK (clk), .D (w[4]), .Q (w[5]));
  DFFRHQX1 d4_qout_reg(.RN (rst), .CK (clk), .D (w[3]), .Q (w[4]));
  DFFRHQX1 d3_qout_reg(.RN (rst), .CK (clk), .D (w[2]), .Q (w[3]));
  DFFRHQX1 d2_qout_reg(.RN (rst), .CK (clk), .D (w[1]), .Q (w[2]));
  DFFRHQX1 d1_qout_reg(.RN (rst), .CK (clk), .D (w[0]), .Q (w[1]));
  DFFRHQX1 d0_qout_reg(.RN (rst), .CK (clk), .D (d), .Q (w[0]));
  INVXL g48(.A (rst), .Y (n_0));
  DFFRX1 d7_qout_reg(.RN (rst), .CK (clk), .D (w[6]), .Q (qout), .QN
       (n_2));
endmodule

